package exception;

public class TestMath {

	public static void main(String[] args) {
		Math math = new Math();
		tr{
		int result = math.division(10, 4);
		}catch(Exception ex){
			System.out.println("You are dividing a number by zero");
			ex.printStackTrace();
		}
		System.out.println(result);

	}

}
